### ISSUE TITLE
长时间不动，服务端会输出EOF

### ISSUE THREAD

**Issue by anlityli** [leffss/gowebssh#1]
长时间不动，没有任何输入，再次输入服务端会EOF，此时ssh可能是与服务器已经断开连接了。能否增加心跳，来保活？

**Comment by leffss** [comment]
这个项目只是试验性的，如果真的要加入堡垒机，是需要考虑这方面的东西的

**Comment by anlityli** [comment]
嗯

**Comment by leffss** [comment]
![捕获](https://user-images.githubusercontent.com/49055524/83827695-85d78c80-a711-11ea-8a60-756d46ce8525.PNG)

我测试了一下，闲置了10几个小时都没有断开呢，你的具体情况是？

**Comment by anlityli** [comment]
我链接的是阿里云服务器，可能阿里云对长连接的时间有控制，然后我用定时器，每隔一段时间发送了一个包解决了这个问题。谢谢！

**Comment by leffss** [comment]
> 我链接的是阿里云服务器，可能阿里云对长连接的时间有控制，然后我用定时器，每隔一段时间发送了一个包解决了这个问题。谢谢！

能否分享一下你的具体实现代码呢？

**Comment by anlityli** [comment]
你的服务器能链接10几个小时不断，可能是服务器的/etc/ssh/ssh_config文件配置了
```
TCPKeepAlive yes
ServerAliveInterval 30
```
我的代码是在 newSSHXtermSession方法中加了一个定时器，定时器内的代码是：
```
if _, err := session.SendRequest("keepalive@golang.org", true, nil); err != nil {
    errors.Wrap(err, "failed to send keep alive")
}
```

**Comment by leffss** [comment]
> 你的服务器能链接10几个小时不断，可能是服务器的/etc/ssh/ssh_config文件配置了

我的服务器不断那是因为TMOUT的设置的原因，我是意思分享下你的心跳方案

**Comment by anlityli** [comment]
定时器，我用的是gf框架带的时间轮定时器，因为go默认的定时器可能有性能问题

**Comment by leffss** [comment]
> 定时器，我用的是gf框架带的时间轮定时器，因为go默认的定时器可能有性能问题

比如说你采用了gf定时器，到了一定时间后会向后端服务器发送什么心跳数据呢？

**Comment by anlityli** [comment]
我上面发了代码了

**Comment by anlityli** [comment]
```
if _, err := session.SendRequest("keepalive@golang.org", true, nil); err != nil {
    errors.Wrap(err, "failed to send keep alive")
}
```

**Comment by leffss** [comment]
看到了，谢谢，学习了

**Comment by anlityli** [comment]
客气，我从你的代码中学到的更多！😁
