### ISSUE TITLE
使用sz 连续下载文件问题

### ISSUE THREAD

**Issue by duxubo** [leffss/gowebssh#2]
请问 使用sz 连续下载文件  第一次可以成功 第二次就卡死，是什么原因，如何解决  谢谢
![image](https://user-images.githubusercontent.com/57305485/111009204-f660b780-83cd-11eb-861d-47a2c07e0a18.png)

**Comment by leffss** [comment]
我测试了下，没有问题呢

![捕获](https://user-images.githubusercontent.com/49055524/111111854-1218b900-859a-11eb-9fcc-a19e4c6a6c53.PNG)

**Comment by duxubo** [comment]
我测试了centos  也没有问题的，但是在deepin  上会出现连续下载卡死

**Comment by leffss** [comment]
> 我测试了centos 也没有问题的，但是在deepin 上会出现连续下载卡死

我只测试了centos 7.6，你的deepin什么版本？然后lrzsz软件啥版本？

**Comment by leffss** [comment]
最新代码已解决

![捕获](https://user-images.githubusercontent.com/49055524/112286649-7d633900-8cc6-11eb-9153-7a98877bdd19.PNG)

**Comment by duxubo** [comment]
nice   你改了什么地方的代码    还是非常感谢

**Comment by duxubo** [comment]
看到了你上次更新的代码，非常感谢。
老乡 你这段代码没有看懂，是什么意思
![image](https://user-images.githubusercontent.com/57305485/113512636-17b15f80-9598-11eb-83fe-7af738060753.png)
我注释了以后页面的命令内容太长导致会覆盖当前行的内容的问题也解决了

**Comment by leffss** [comment]
> 看到了你上次更新的代码，非常感谢。
> 老乡 你这段代码没有看懂，是什么意思
> ![image](https://user-images.githubusercontent.com/57305485/113512636-17b15f80-9598-11eb-83fe-7af738060753.png)
> 我注释了以后页面的命令内容太长导致会覆盖当前行的内容的问题也解决了

限制终端行列长度的，注不注释都可以
