### ISSUE TITLE
是否可以限制 shell命令执行

### ISSUE THREAD

**Issue by duxubo** [leffss/gowebssh#5]
请问是否可以在执行命令前 校验当前要执行的指令是否在限制范围，tks

**Comment by leffss** [comment]
> 请问是否可以在执行命令前 校验当前要执行的指令是否在限制范围，tks

理论上是可以的，但是比较麻烦，并且限制功能是很容易失效的，比如限制 reboot 命令，可以很简单的跳过：
```
a=re && b=oot &&  ${a}b${b}
```
