### ISSUE TITLE
上传大文件会一直卡在99%

### ISSUE THREAD

**Issue by duxubo** [leffss/gowebssh#6]
你好 请问这是为什么 upload gin-vue-admin.zip: 92.0 MB 92.8 MB 99%

**Comment by leffss** [comment]
> 你好 请问这是为什么 upload gin-vue-admin.zip: 92.0 MB 92.8 MB 99%

我的微信：leffss  你加一下把 gin-vue-admin.zip 发我试试

**Comment by duxubo** [comment]
我已添加你的微信，麻烦通过下，
![image](https://user-images.githubusercontent.com/57305485/140073782-4fbd90cf-c47e-45d6-b585-acbe5cce6ce9.png)
你看文件上传到最后一点就卡了，只要是稍微大一点的文件就有这个问题
