### ISSUE TITLE
带有私钥短语的密钥登录

### ISSUE THREAD

**Issue by staugur** [leffss/gowebssh#8]
我正在用examples测试功能，常用命令都挺好，尤其是上传、下载。

有一项支持，测试密钥登录时，假如有密码短语的话，修改后可以实现，大佬为啥没有加呢？我的修改大概是（复用password，选择密钥类型时直接用它作为私钥密码）：
1. message.go messgae 结构增加字段：
```go
+       Passphrase []byte      `json:"passphrase,omitempty"`
```

2. webssh.go 读取密码短语
```go
+                       passphrase, _ := UrlQueryUnescape(string(msg.Passphrase))
.
.
.
-                       signer, err := ssh.ParsePrivateKey(pemBytes)
+                       var signer ssh.Signer
+                       var err error
+                       if passphrase != "" {
+                               signer, err = ssh.ParsePrivateKeyWithPassphrase(pemBytes, []byte(passphr
ase))
+                       } else {
+                               signer, err = ssh.ParsePrivateKey(pemBytes)
+                       }
```

3. 前端 webssh.js 发送publickey类型时，附上了passphrase字段
```js
-                       socket.send(JSON.stringify({ type: "publickey", data: utf8_to_b64(connect_info.s
sh_key) }));
+                       socket.send(JSON.stringify({ type: "publickey", data: utf8_to_b64(connect_info.s
sh_key), passphrase: utf8_to_b64(connect_info.passwd) }));
```

----
另外，有个好奇点，前端 utf8、base64互转，escape、unescape是因为 go UrlQueryUnescape？不过这俩函数标准已经废弃没关系吗？

**Comment by leffss** [comment]
密钥有密码的是前面没有考虑这种情况，可以考虑参考你的方法加上；

后面的转码没看懂你什么意思；

**Comment by staugur** [comment]
我提交下PR吧，回头应该要使用这个库实现下我们的需求。

---

webssh.js
```js
function utf8_to_b64(rawString) {
	return btoa(unescape(encodeURIComponent(rawString)));
}

function b64_to_utf8(encodeString) {
	return decodeURIComponent(escape(atob(encodeString)));
}
```
这里的 [escape](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/escape) 必须的吗

**Comment by leffss** [comment]
> 我提交下PR吧，回头应该要使用这个库实现下我们的需求。
> 
> webssh.js
> 
> ```js
> function utf8_to_b64(rawString) {
> 	return btoa(unescape(encodeURIComponent(rawString)));
> }
> 
> function b64_to_utf8(encodeString) {
> 	return decodeURIComponent(escape(atob(encodeString)));
> }
> ```
> 
> 这里的 [escape](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/escape) 必须的吗

必须的
